import { ThemeProvider } from '@theme-ui/core';
import { toTheme } from '@theme-ui/typography';
import Head from 'next/head';
import Image from 'next/image';
import grandViewTheme from "typography-theme-grand-view";
import styles from 'styles/Home.module.css';
import Footer from 'components/Footer';
import Header from 'components/Header';

const theme = toTheme(grandViewTheme);

const colors = {
    text: '#000',
    background: '#fff',
    primary: '#b80f0d',
    secondary: '#096E6E',
    accent: '#D30000',
}

const MainLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <ThemeProvider theme={{ ...theme, colors }}>

            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <Header />

                    {children}

                </main >
                <Footer />
            </div>
        </ThemeProvider >
    )
};

export default MainLayout;